<div style="display: flex; background-color: RGB(255,114,0);" >
<div>
<img src="img/fraudeur_-_BNPP_PF_-_finale.jpg" width="300"/>
</div>

# PROJET - Comment démasquer les fraudeurs ? <mark>EDA / Pré-processing</mark>
</div>

par BNP Paribas PF

Lien vers le challenge : https://challengedata.ens.fr/participants/challenges/104/

<div style="display: flex; background-color: Blue; padding: 15px;" >

## 1.CHARGEMENT des données
</div>

In [1]:
from os import getcwd
from os.path import join
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.core.display import HTML

import warnings
warnings.filterwarnings("ignore")

from bnp_paribas_preprocessing import *
from bnp_paribas_util import *
from bnp_paribas_util_graph import color_graph_background

# ---------------------------------------------------------------------------------------------
#                               MAIN
# ---------------------------------------------------------------------------------------------
verbose = 1
short_name = "MAIN"
target = "fraud_flag"

project_name = "projet_bnp_paribas_fraudeurs"
# Récupère le répertoire du programme
execution_path = getcwd().split("projet_")[0]
execution_path = join(execution_path, project_name)

data_set_path = join(execution_path, 'dataset')

files_name = {
    'X_train' : "X_train_G3tdtEn.csv",
    'y_train' : "Y_train_2_XPXJDyy.csv",
    'X_test_challenge' : "X_test_8skS2ey.csv",
}

print(f"Current execution path : {execution_path}")
print(f"Dataset path : {data_set_path}")

Current execution path : c:\Users\User\WORK\workspace-ia\PROJETS\projet_bnp_paribas_fraudeurs
Dataset path : c:\Users\User\WORK\workspace-ia\PROJETS\projet_bnp_paribas_fraudeurs\dataset

In [2]:
dataset_dict = {}

for set_name, file_name in files_name.items():
    dataset_dict[set_name] = load_dump_file(data_set_path=data_set_path, file_name=file_name)
    info(short_name,f"{set_name:<15} {dataset_dict[set_name].shape} données chargées")

X_train_origin, y_train_origin, X_test_challenge_origin = dataset_dict.get("X_train", None), dataset_dict.get("y_train", None), dataset_dict.get("X_test_challenge", None)

[MAIN                ]	INFO  X_train         (92790, 146) données chargées
[MAIN                ]	INFO  y_train         (92790, 2) données chargées
[MAIN                ]	INFO  X_test_challenge (23198, 146) données chargées

In [3]:
file_name_start = f"{datetime.now().strftime('%Y-%m-%d_%H-%M')}"
file_name_start = '2023-02-16_15-36'
file_name_start

'2023-02-16_15-36'

In [4]:
creat_dir(dest_path=join(data_set_path, file_name_start), verbose=verbose)

<div style="display: flex; background-color: Blue; padding: 15px;" >

## 2.EDA
</div>

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.1. Visualisation
</div>

In [4]:
X_train_origin

,ID,item1,item2,item3,item4,item5,item6,item7,item8,item9,...,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24,Nb_of_items
0,85517,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,51113,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,83008,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,78712,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,77846,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92785,21243,COMPUTER PERIPHERALS ACCESSORIES,FULFILMENT CHARGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
92786,45891,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
92787,42613,BEDROOM FURNITURE,BEDROOM FURNITURE,OUTDOOR FURNITURE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
92788,43567,COMPUTERS,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
92789,68268,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [5]:
y_train_origin

          ID  fraud_flag
index
0      85517           0
1      51113           0
2      83008           0
3      78712           0
4      77846           0
...      ...         ...
92785  21243           0
92786  45891           0
92787  42613           0
92788  43567           0
92789  68268           0

[92790 rows x 2 columns]

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.1. Pre-Processing => Nettoyage
</div>

Nettoyage : Après plusieurs visualisations, il s'avère que les items sont dupliqués, car ils ont des écritures différentes.
- à l'origine il y avait 173 items, après nettoyage => 162 items
- Application du même nettoyage aux autres données Object

Suppression de colonnes non utilisées :
- code des articles : 24 columns droped

In [4]:
# 8.4s de traitement
save_file_path = join(data_set_path, file_name_start, DATASET_FILES_NAMES.get("dataset_preprocess"))
dataset_preprocess = pre_processing(X=X_train_origin, y=y_train_origin, save_file_path=save_file_path, verbose=verbose)
dataset_preprocess

[load_dump_file      ]	INFO  dataset_preprocess.csv LOAD
[pre_processing      ]	INFO  dump file exist (92790, 123) --> LOAD

,ID,Nb_of_items,fraud_flag,item1,item2,item3,item4,item5,item6,item7,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
index,,,,,,,,,,,,,,,,,,,,,
0,85517,1.0,0,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51113,1.0,0,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,83008,1.0,0,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,78712,2.0,0,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,77846,1.0,0,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92785,21243,2.0,0,COMPUTER PERIPHERALS ACCESSORIES,FULFILMENT CHARGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92786,45891,1.0,0,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92787,42613,3.0,0,BEDROOM FURNITURE,BEDROOM FURNITURE,OUTDOOR FURNITURE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92788,43567,2.0,0,COMPUTERS,COMPUTERS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92789,68268,1.0,0,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# 3,8s de traitement
save_file_path = join(data_set_path, file_name_start, DATASET_FILES_NAMES.get("dataset_test_preprocess"))
dataset_test_preprocess = pre_processing(X=X_test_challenge_origin, y=None, save_file_path=save_file_path, verbose=verbose)

[load_dump_file      ]	INFO  dataset_test_challenge_preprocess.csv LOAD
[pre_processing      ]	INFO  dump file exist (23198, 122) --> LOAD

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.4. Encodage des données
</div>

<div style="display: flex; background-color: indigo;" >

#### 2.4.1. TRAIN
</div>

In [6]:
# /!\ 50 min de traitement lors du forçage
# /!\ 306 min soit 5h de traitement lors du forçage ou 412 min soit 6h50
# 25 s si déjà traité et sauvegardé
dataset_encoded = encode_data(df=dataset_preprocess, 
                                data_set_path=join(data_set_path, file_name_start), 
                                file_name=DATASET_FILES_NAMES.get("dataset_encoded"),
                                force=0, with_drop=1, to_encode_data=['item', 'make'], add_item_group=0,
                                verbose=verbose)
print(dataset_encoded.shape)
dataset_encoded

[load_dump_file      ]	INFO  dataset_encoded.csv LOAD
(92790, 1984)

,ID,Nb_of_items,fraud_flag,item_JEWELLERYWATCHES_nb,item_JEWELLERYWATCHES_cash,item_FILING DESK ACCESSORIES_nb,item_FILING DESK ACCESSORIES_cash,item_HOUSEHOLD CLEANING_nb,item_HOUSEHOLD CLEANING_cash,item_HOME OFFICE_nb,...,make_TED BAKER_cash,make_LOLA ROSE_nb,make_LOLA ROSE_cash,make_MOTHER OF PEARL_nb,make_MOTHER OF PEARL_cash,make_ROCKET DOG_nb,make_ROCKET DOG_cash,make_BOORI_nb,make_BOORI_cash,amount
index,,,,,,,,,,,,,,,,,,,,,
0,85517,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,889.0
1,51113,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,409.0
2,83008,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1399.0
3,78712,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,808.0
4,77846,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1199.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92785,21243,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,306.0
92786,45891,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,898.0
92787,42613,3.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1727.0
92788,43567,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,3198.0
92789,68268,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,799.0

Les colonnes numérotées doivent avoir été supprimées à ce niveau

<div style="display: flex; background-color: indigo;" >

#### 2.4.2. TEST
</div>

In [7]:
# 27m 29.5 s de traitement
dataset_test_encoded = encode_data(df=dataset_test_preprocess, 
                                data_set_path=join(data_set_path, file_name_start), 
                                file_name=DATASET_FILES_NAMES.get("dataset_test_encoded"),
                                force=0, with_drop=1, to_encode_data=['item', 'make'], add_item_group=0,
                                verbose=verbose)
print(dataset_test_encoded.shape)
dataset_test_encoded

[encode_data         ]	INFO  (23198, 122) datas to encode
[encode_data         ]	INFO  STEP 0 => remain 2 to encod ['make', 'item']
[drop_numeroted_data_col]	INFO  24 columns droped
[drop_numeroted_data_col]	INFO  0 columns droped
[encode_data         ]	INFO  STEP 1 => 2 unsed columns DROP --> (23198, 98)

  0%|          | 0/2 [00:00<?, ?it/s]

[encode_data         ]	WARN  STEP 2 => encoding MAKE to features ~= 270 min ~= 4h30...
[encode_numeroted_data_to_features]	INFO: Conversion MAKE to feature... START

make_list: 100%|██████████| 470/470 [26:16<00:00,  3.35s/it]

[encode_numeroted_data_to_features]	INFO: Conversion MAKE to feature............ END
[encode_numeroted_data_to_features]	INFO  Drop make columns ...
[drop_numeroted_data_col]	INFO  24 columns droped
[drop_numeroted_data_col]	INFO  0 columns droped

 50%|█████     | 1/2 [26:24<26:24, 1584.16s/it]

[dump_file]	INFO: dataset_test_challenge_encoded_MAKE.csv => SAVED
[encode_data         ]	INFO  STEP 2 => encoding MAKE to features --> (23198, 1014) SAVE
[encode_data         ]	WARN  STEP 2 => encoding ITEM to features > 30 min...
[encode_numeroted_data_to_features]	INFO: Conversion ITEM to feature... START

item_list: 100%|██████████| 142/142 [09:36<00:00,  4.06s/it]

[encode_numeroted_data_to_features]	INFO: Conversion ITEM to feature............ END
[encode_numeroted_data_to_features]	INFO  Drop item columns ...
[drop_numeroted_data_col]	INFO  24 columns droped
[drop_numeroted_data_col]	INFO  0 columns droped

100%|██████████| 2/2 [36:09<00:00, 1084.79s/it]

[dump_file]	INFO: dataset_test_challenge_encoded_ITEM.csv => SAVED
[encode_data         ]	INFO  STEP 2 => encoding ITEM to features --> (23198, 1274) SAVE

[drop_numeroted_data_col]	INFO  48 columns droped
[encode_data         ]	INFO  STEP 3 => columns ['Nbr_of_prod_purchas', 'cash_price'] --> (23198, 1226) DROP
[encode_data         ]	INFO  STEP 4 => Add Amount DONE
[dump_file]	INFO: dataset_test_challenge_encoded.csv => SAVED
(23198, 1227)

,ID,Nb_of_items,make_SODASTREAM_nb,make_SODASTREAM_cash,make_BEABA_nb,make_BEABA_cash,make_SNUGGLEDOWN_nb,make_SNUGGLEDOWN_cash,make_MANHATTAN_nb,make_MANHATTAN_cash,...,item_STORAGE ORGANISATION_cash,item_BLANK MEDIA MEDIA STORAGE_nb,item_BLANK MEDIA MEDIA STORAGE_cash,item_STATIONERY SUNDRIES_nb,item_STATIONERY SUNDRIES_cash,item_IMAGING EQUIPMENT_nb,item_IMAGING EQUIPMENT_cash,item_COMPUTER PERIPHERALS ACCESSORIES_nb,item_COMPUTER PERIPHERALS ACCESSORIES_cash,amount
index,,,,,,,,,,,,,,,,,,,,,
0,64707,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,399.0
1,63919,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,294.0,294.0
2,15664,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,929.0
3,6626,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,546.0
4,26766,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,2470.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23193,63474,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,499.0,516.0
23194,80438,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1189.0
23195,29485,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1649.0
23196,59838,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,369.0,409.0
23197,110584,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1776.0

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.5. Ajout des groupes
</div>

<mark>Ce traitement est inclus dans le pré-processing</mark>

In [55]:
add_item_group = 1

In [112]:
print(dataset_test_encoded.shape)

(23198, 1227)

In [154]:
dataset_encoded.shape

(92790, 1984)

In [155]:
# 40,4 sec de traitement pour test
file_name=DATASET_FILES_NAMES.get("dataset_encoded")
save_file_path = join(data_set_path, file_name_start, file_name)

# 1. Ajouter les groupes pour les items
if verbose>1: debug(short_name, f"STEP 4 => Group items")
with_drop= 1 if add_item_group == 2 else 0
f_name = save_file_path.replace(".csv", f'_groups.csv')
dataset_encoded = add_item_group_datas_to_features(df=dataset_encoded,data_set_path=f_name, with_drop=with_drop, verbose=verbose)
if verbose>0:
    info(short_name, f"STEP 4 => Group items {surligne_text('DONE')}")
print(dataset_encoded.shape)

[prefixed_cols]	INFO: 324 columns prefixed by item
[dump_file]	INFO: dataset_encoded_groups.csv => SAVED
[add_item_group_datas_to_features]	INFO  (92790, 2040) result data.
[MAIN                ]	INFO  STEP 4 => Group items DONE
(92790, 2040)

In [156]:
dataset_encoded.shape

(92790, 2040)

In [158]:
dump_file(data_set_path=save_file_path, df=dataset_encoded, verbose=verbose)

[dump_file]	INFO: dataset_encoded.csv => SAVED

'c:\\Users\\User\\WORK\\workspace-ia\\PROJETS\\projet_bnp_paribas_fraudeurs\\dataset\\2023-02-16_15-36\\dataset_encoded.csv'

In [142]:
# 40,4 sec de traitement pour test
file_name=DATASET_FILES_NAMES.get("dataset_test_encoded")
save_file_path = join(data_set_path, file_name_start, file_name)

# 1. Ajouter les groupes pour les items
if verbose>1: debug(short_name, f"STEP 4 => Group items")
with_drop= 1 if add_item_group == 2 else 0
f_name = save_file_path.replace(".csv", f'_groups.csv')
dataset_test_encoded = add_item_group_datas_to_features(df=dataset_test_encoded,data_set_path=f_name, with_drop=with_drop, verbose=verbose)
if verbose>0:
    info(short_name, f"STEP 4 => Group items {surligne_text('DONE')}")
print(dataset_test_encoded.shape)

[prefixed_cols]	INFO: 284 columns prefixed by item
[clean_groups        ]	INFO  COMPUTER => 2 NB + 2 cash columns to proceed
[clean_groups        ]	INFO  COMPUTER ACCESSORIES => 11 NB + 11 cash columns to proceed
[clean_groups        ]	INFO  SOFTWARE => 2 NB + 2 cash columns to proceed
[clean_groups        ]	INFO  AUDIO ACCESSORIES => 1 NB + 1 cash columns to proceed
[clean_groups        ]	INFO  BABY => 6 NB + 6 cash columns to proceed
[clean_groups        ]	INFO  BAGS => 5 NB + 5 cash columns to proceed
[clean_groups        ]	INFO  OUTDOOR ACCESSORIES => 5 NB + 5 cash columns to proceed
[clean_groups        ]	INFO  BEAUTY AND SAFETY => 12 NB + 12 cash columns to proceed
[clean_groups        ]	INFO  HOUSE LINEN => 11 NB + 11 cash columns to proceed
[clean_groups        ]	INFO  HOUSE ACCESSORIES => 30 NB + 30 cash columns to proceed
[clean_groups        ]	INFO  CHILDRENS => 6 NB + 6 cash columns to proceed
[clean_groups        ]	INFO  NURSERY => 4 NB + 4 cash columns to proceed
[clean_groups        ]	INFO  WOMEN => 4 NB + 4 cash columns to proceed
[clean_groups        ]	INFO  MEN => 5 NB + 5 cash columns to proceed
[clean_groups        ]	INFO  CABLES ADAPTERS => 2 NB + 2 cash columns to proceed
[clean_groups        ]	INFO  BOOKS => 1 NB + 1 cash columns to proceed
[clean_groups        ]	INFO  OFFICE ACCESSORIES => 5 NB + 5 cash columns to proceed
[clean_groups        ]	INFO  GAMES => 2 NB + 2 cash columns to proceed
[clean_groups        ]	INFO  SPORT => 2 NB + 2 cash columns to proceed
[clean_groups        ]	INFO  POWER ACCESSORIES => 3 NB + 3 cash columns to proceed
[clean_groups        ]	INFO  HI-FI => 4 NB + 4 cash columns to proceed
[clean_groups        ]	INFO  FOOD => 4 NB + 4 cash columns to proceed
[clean_groups        ]	INFO  IMAGING EQUIPMENT => 1 NB + 1 cash columns to proceed
[clean_groups        ]	INFO  JEWELLERY => 1 NB + 1 cash columns to proceed
[clean_groups        ]	INFO  TELEPHONE ACCESSORIES => 3 NB + 3 cash columns to proceed
[clean_groups        ]	INFO  OTHER => 4 NB + 4 cash columns to proceed
[clean_groups        ]	INFO  SERVICE => 2 NB + 2 cash columns to proceed
[dump_file]	INFO: dataset_test_challenge_encoded_groups.csv => SAVED
[add_item_group_datas_to_features]	INFO  (23198, 1283) result data.
[MAIN                ]	INFO  STEP 4 => Group items DONE
(23198, 1283)

In [150]:
dump_file(data_set_path=save_file_path, df=dataset_test_encoded, verbose=verbose)

[dump_file]	INFO: dataset_test_challenge_encoded.csv => SAVED

'c:\\Users\\User\\WORK\\workspace-ia\\PROJETS\\projet_bnp_paribas_fraudeurs\\dataset\\2023-02-16_15-36\\dataset_test_challenge_encoded.csv'

In [120]:
data_col_name = "item"
unk_cash = "group_"+data_col_name+"_"+UNKNOWN_KEY+"_cash"
unk_nb = "group_"+data_col_name+"_"+UNKNOWN_KEY+"_nb"

In [ ]:
# 2. Voir s'il faut les ajouter aussi pour les marques

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.6. Traitement des valeurs de tests inconnues du train
</div>

In [ ]:
# file_name= "test_complete_encoded_2023_01_19.csv"
data_set_test_file_name = join(data_set_path, DATASET_FILES_NAMES.get('dataset_test_encoded'))
test_origin = test_encode_to_train_compatibility(file_path=data_set_test_file_name, train_columns=dataset_encoded.columns, verbose=verbose)
test_origin

[load_dump_file      ]	INFO  dataset_test_challenge_encoded.csv LOAD
[df_memory           ]	INFO  3,496.37 Ko (bytes) 	--> 3.50 Mo	--> 0.00 Go
[df_dense_to_sparse  ]	INFO  238,289.86 bytes before 	--> 3,496.37 Ko after --> 	 -234793.484 Ko
[df_dense_to_sparse  ]	INFO  Sparse.density : 0.01
[load_dump_file      ]	INFO  dataset_test_challenge_encoded.csv COMPRESS
[add_amounts         ]	INFO  The column amount ever in df.
[preprocess_test_df  ]	INFO  (23198, 2039) test données mises à jour (on load : (23198, 1283))
[dump_file           ]	WARN  dataset_test_challenge_train_compatible.csv : Impossible to uncompress data : Can only use the '.sparse' accessor with Sparse data.
[dump_file           ]	INFO  dataset_test_challenge_train_compatible.csv => SAVED
[preprocess_test_df  ]	INFO  (23198, 2039) test données chargées

,ID,Nb_of_items,item_JEWELLERYWATCHES_nb,item_JEWELLERYWATCHES_cash,item_FILING DESK ACCESSORIES_nb,item_FILING DESK ACCESSORIES_cash,item_HOUSEHOLD CLEANING_nb,item_HOUSEHOLD CLEANING_cash,item_HOME OFFICE_nb,item_HOME OFFICE_cash,...,group_item_JEWELLERY_nb,group_item_JEWELLERY_cash,group_item_TELEPHONE ACCESSORIES_nb,group_item_TELEPHONE ACCESSORIES_cash,group_item_OTHER_nb,group_item_OTHER_cash,group_item_SERVICE_nb,group_item_SERVICE_cash,group_item_UNKNOWN_cash,group_item_UNKNOWN_nb
index,,,,,,,,,,,,,,,,,,,,,
0,64707,1.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
1,63919,1.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
2,15664,1.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
3,6626,2.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
4,26766,1.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23193,63474,2.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
23194,80438,1.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
23195,29485,1.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0
23196,59838,2.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,1,40.0,0.0,0
23197,110584,2.0,0,0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,0.0,0

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.7. Piste de traitements supplémentaires
</div>

Testé et KO :
- ACP => pas de résultat intéressant
- 

1. Diminuer le nombre de colonne en affectant certaines colonnes à UNKNOWN (avec et sans fraude)
1. Ajouter des tranches de montant
1.

In [159]:
# 1. Supprimer des colonnes (avec et sans fraude) et les mettre dans UNKNOWN

# 2. Vérifier si test a des colonnes non connues et dans ce cas les mettre dans UNKNOWN

# 3. Regarder la nouvelle taille des DF

<div style="display: flex; background-color: Green; padding: 7px;" >

### 2.7. Conversion en matrices creuses
</div>

In [20]:
# 0. Etat initial en mémoire
dataset_encoded_memory = df_memory(df=dataset_encoded, verbose=verbose)
dataset_test_encoded_memory = df_memory(df=dataset_test_encoded, verbose=verbose)

[MAIN                ]	INFO  DF dense : 1,473,505.20 Koctets (bytes) 	--> 1,473.51 Mo	--> 1.47 Go
[MAIN                ]	INFO  DF dense : 43,333.86 Koctets (bytes) 	--> 43.33 Mo	--> 0.04 Go

In [33]:
dataset_encoded_sparse1 = df_dense_to_sparse(dataset_encoded, verbose=verbose)
dataset_encoded_sparse1

[MAIN                ]	INFO  DF dense : 10,640.60 Ko (bytes) 	--> 10.64 Mo	--> 0.01 Go
[df_dense_to_sparse  ]	INFO  1473505.20 bytes before 	--> 10640.60 Ko after --> 	 -1462864.596 Ko
[df_dense_to_sparse  ]	INFO  Sparse.density : 0.00

,ID,Nb_of_items,fraud_flag,item_JEWELLERYWATCHES_nb,item_JEWELLERYWATCHES_cash,item_FILING DESK ACCESSORIES_nb,item_FILING DESK ACCESSORIES_cash,item_HOUSEHOLD CLEANING_nb,item_HOUSEHOLD CLEANING_cash,item_HOME OFFICE_nb,...,make_TED BAKER_cash,make_LOLA ROSE_nb,make_LOLA ROSE_cash,make_MOTHER OF PEARL_nb,make_MOTHER OF PEARL_cash,make_ROCKET DOG_nb,make_ROCKET DOG_cash,make_BOORI_nb,make_BOORI_cash,amount
index,,,,,,,,,,,,,,,,,,,,,
0,85517,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,889.0
1,51113,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,409.0
2,83008,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1399.0
3,78712,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,808.0
4,77846,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1199.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92785,21243,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,306.0
92786,45891,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,898.0
92787,42613,3.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1727.0
92788,43567,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,3198.0
92789,68268,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,799.0

In [32]:
dataset_test_encoded_sparse1 = df_dense_to_sparse(dataset_test_encoded, verbose=verbose)
dataset_test_encoded_sparse1

[MAIN                ]	INFO  DF dense : 1,768.86 Ko (bytes) 	--> 1.77 Mo	--> 0.00 Go
[df_dense_to_sparse  ]	INFO  1768.86 bytes before 	--> 1768.86 Ko after --> 	 0.0 Ko
[df_dense_to_sparse  ]	INFO  Sparse.density : 0.01

,ID,Nb_of_items,make_SODASTREAM_nb,make_SODASTREAM_cash,make_BEABA_nb,make_BEABA_cash,make_SNUGGLEDOWN_nb,make_SNUGGLEDOWN_cash,make_MANHATTAN_nb,make_MANHATTAN_cash,...,item_STORAGE ORGANISATION_cash,item_BLANK MEDIA MEDIA STORAGE_nb,item_BLANK MEDIA MEDIA STORAGE_cash,item_STATIONERY SUNDRIES_nb,item_STATIONERY SUNDRIES_cash,item_IMAGING EQUIPMENT_nb,item_IMAGING EQUIPMENT_cash,item_COMPUTER PERIPHERALS ACCESSORIES_nb,item_COMPUTER PERIPHERALS ACCESSORIES_cash,amount
index,,,,,,,,,,,,,,,,,,,,,
0,64707,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,399.0
1,63919,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,294.0,294.0
2,15664,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,929.0
3,6626,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,546.0
4,26766,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,2470.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23193,63474,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,499.0,516.0
23194,80438,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1189.0
23195,29485,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1649.0
23196,59838,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,369.0,409.0
23197,110584,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1776.0

In [47]:
to_dense = df_sparse_to_dense(df=dataset_encoded, verbose=verbose)
to_dense

[df_memory           ]	INFO  10,640.60 Ko (bytes) 	--> 10.64 Mo	--> 0.01 Go
[df_sparse_to_dense  ]	INFO  10,640.60 Ko before 	--> 10,640.60 Ko after --> 	 0.0 Ko

,ID,Nb_of_items,fraud_flag,item_JEWELLERYWATCHES_nb,item_JEWELLERYWATCHES_cash,item_FILING DESK ACCESSORIES_nb,item_FILING DESK ACCESSORIES_cash,item_HOUSEHOLD CLEANING_nb,item_HOUSEHOLD CLEANING_cash,item_HOME OFFICE_nb,...,make_TED BAKER_cash,make_LOLA ROSE_nb,make_LOLA ROSE_cash,make_MOTHER OF PEARL_nb,make_MOTHER OF PEARL_cash,make_ROCKET DOG_nb,make_ROCKET DOG_cash,make_BOORI_nb,make_BOORI_cash,amount
index,,,,,,,,,,,,,,,,,,,,,
0,85517,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,889.0
1,51113,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,409.0
2,83008,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1399.0
3,78712,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,808.0
4,77846,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1199.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92785,21243,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,306.0
92786,45891,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,898.0
92787,42613,3.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1727.0
92788,43567,2.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,3198.0
92789,68268,1.0,0,0,0.0,0,0.0,0,0.0,0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,799.0

In [44]:
to_dense = df_sparse_to_dense(df=dataset_test_encoded_sparse1, verbose=verbose)
to_dense

[df_memory           ]	INFO  1,768.86 Ko (bytes) 	--> 1.77 Mo	--> 0.00 Go
[df_sparse_to_dense  ]	INFO  1,768.86 bytes before 	--> 1,768.86 Ko after --> 	 0.0 Ko

,ID,Nb_of_items,make_SODASTREAM_nb,make_SODASTREAM_cash,make_BEABA_nb,make_BEABA_cash,make_SNUGGLEDOWN_nb,make_SNUGGLEDOWN_cash,make_MANHATTAN_nb,make_MANHATTAN_cash,...,item_STORAGE ORGANISATION_cash,item_BLANK MEDIA MEDIA STORAGE_nb,item_BLANK MEDIA MEDIA STORAGE_cash,item_STATIONERY SUNDRIES_nb,item_STATIONERY SUNDRIES_cash,item_IMAGING EQUIPMENT_nb,item_IMAGING EQUIPMENT_cash,item_COMPUTER PERIPHERALS ACCESSORIES_nb,item_COMPUTER PERIPHERALS ACCESSORIES_cash,amount
index,,,,,,,,,,,,,,,,,,,,,
0,64707,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,399.0
1,63919,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,294.0,294.0
2,15664,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,929.0
3,6626,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,546.0
4,26766,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,2470.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23193,63474,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,499.0,516.0
23194,80438,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1189.0
23195,29485,1.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1649.0
23196,59838,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,1,369.0,409.0
23197,110584,2.0,0,0.0,0,0.0,0,0.0,0,0.0,...,0.0,0,0.0,0,0.0,0,0.0,0,0.0,1776.0

In [ ]:
from scipy import sparse

In [ ]:
# 1. Convertir les DF en matrice creuses

def df_to_sparse(df, verbose=0):
    #  CSR pour Compressed sparse row
    my_matrix = sparse.csr_matrix(df.values)
    # Conversion via COO matrix
    coo = sparse.coo_matrix((df["rating"], (user_index, movie_index)), shape=shape)
    csr = coo.tocsr()


    return my_matrix

# 2. Sauvegarder le résultat

# 3. Ecrire fonction conversion / déconversion

In [ ]:
# 1. remplacement des valeurs 0 par np.nan
def fill_value_by_other(df, to_replace=0, replace_by = np.nan, verbose=0):
    """Replace all DF values = `to_replace` by `replace_by`

    Args:
        df (DataFrame): _description_
        to_replace (int or str), optional):Value to replace. Defaults to 0.
        replace_by (int or str), optional):Replacement value. Defaults to np.nan.
        verbose (int, optional): _description_. Defaults to 0.

    Returns:
        DataFrame: The updated DataFrame
    """
    short_name = "fill_zero_by_na"
    na_before = df.isna().sum().sum()
    m_before = df.memory_usage().sum() / 1e3
    for col in df.columns:
        df.loc[df[col]==to_replace, col] = replace_by
    if verbose>0:
        na_after = df.isna().sum().sum()
        info(short_name, f"{na_before} NA before \t--> {na_after} NA After --> \t {na_after-na_before} NA")
        m_after = df.memory_usage().sum() / 1e3
        info(short_name, f'{m_before:0.2f} bytes before \t--> {m_after:0.2f} bytes after --> \t {m_after-m_before} bytes')
    return df

In [ ]:
dataset_encoded_na = fill_value_by_other(df=dataset_encoded, verbose=verbose)

In [ ]:
dataset_test_encoded_na = fill_value_by_other(df=dataset_test_encoded, verbose=verbose)

In [ ]:
# 1. Convertir les DF en matrice creuses
def df_dense_to_sparse_old(df, verbose=0):
    short_name = "df_dense_to_sparse"
    #  CSR pour Compressed sparse row
    my_matrix = sparse.csr_matrix(df.values)
    if verbose>0:
        info(short_name, f'Sparse.density : {my_matrix.sparse.density:0.2f}')
    return my_matrix