<div style="display: flex; background-color: RGB(255,114,0);" >
<div>
<img src="img/fraudeur_-_BNPP_PF_-_finale.jpg" width="300"/>
</div>

# PROJET - Comment démasquer les fraudeurs ? <mark>EDA toutes les données</mark>
</div>

par BNP Paribas PF

Lien vers le challenge : https://challengedata.ens.fr/participants/challenges/104/

<div style="display: flex; background-color: Blue; padding: 15px;" >

## 1.CHARGEMENT des données
</div>

In [2]:
from os import getcwd
from os.path import join
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

from bnp_paribas import *

# ---------------------------------------------------------------------------------------------
#                               MAIN
# ---------------------------------------------------------------------------------------------
verbose = 1
target = "fraud_flag"

# Récupère le répertoire du programme
execution_path = getcwd().split("projet_bnp_paribas_fraudeurs")[0]
execution_path = join(execution_path, 'projet_bnp_paribas_fraudeurs')

data_set_path = join(execution_path, 'dataset')
data_set_train_file_name = join(data_set_path, "train_complete_encoded_hyper_light_2023_01_19.csv")

print(f"Current execution path : {execution_path}")
print(f"Dataset path : {data_set_path}")

Current execution path : c:\Users\User\WORK\workspace-ia\PROJETS\projet_bnp_paribas_fraudeurs
Dataset path : c:\Users\User\WORK\workspace-ia\PROJETS\projet_bnp_paribas_fraudeurs\dataset

<div style="display: flex; background-color: Blue; padding: 15px;" >

## 4.Test des models avec les données ajoutées
</div>

In [2]:
over_name = "SMOTE_minority"
# Chargement des données
path = join(data_set_path,OVERED_DATASET_FILE_NAME.get(over_name)) 
dataset_over = load_over_dataset(path, verbose=verbose)
print(dataset_over[target].value_counts())
dataset_over

[load_over_dataset   ]	INFO  (146370, 1982) datas LOAD
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                float64
item_BED LINEN_nb          float64
item_BED LINEN_cash        float64
item_BATHROOM_nb           float64
                            ...
make_TEMPLE ISLAND_cash    float64
make_GHD_nb                float64
make_GHD_cash              float64
amount                     float64
fraud_flag                   int64
Length: 1982, dtype: object
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                float16
item_BED LINEN_nb             int8
item_BED LINEN_cash        float16
item_BATHROOM_nb              int8
                            ...
make_TEMPLE ISLAND_cash    float16
make_GHD_nb                   int8
make_GHD_cash              float16
amount                     float16
fraud_flag                    int8
Length: 1982, dtype: object
0    73185
1    73185
Name: fraud_flag, dtype: int64

,ID,Nb_of_items,item_BED LINEN_nb,item_BED LINEN_cash,item_BATHROOM_nb,item_BATHROOM_cash,item_DISPOSABLE TABLEWARE CUTLERY_nb,item_DISPOSABLE TABLEWARE CUTLERY_cash,item_TOYS_nb,item_TOYS_cash,...,make_ROLSER_nb,make_ROLSER_cash,make_DARTINGTON CRYSTAL_nb,make_DARTINGTON CRYSTAL_cash,make_TEMPLE ISLAND_nb,make_TEMPLE ISLAND_cash,make_GHD_nb,make_GHD_cash,amount,fraud_flag
index,,,,,,,,,,,,,,,,,,,,,
12214,79535,1.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1197.0,0
21619,56408,3.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1635.0,0
18886,14674,1.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,2640.0,0
85690,33513,3.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1873.0,1
30417,65918,1.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1249.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68134,68126,1.049805,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1728.0,1
58992,91369,1.070312,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,855.0,1
1548,48205,1.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1582.0,1
52814,98028,1.000000,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1900.0,1
37615,92630,3.480469,0,0.0,0,0.0,0,0.0,0,0.0,...,0,0.0,0,0.0,0,0.0,0,0.0,1305.0,1

In [3]:
save_path = path.replace(".csv", "_rounded.csv")
dataset_over.to_csv(save_path, index_label="index")

In [4]:
for over_name in OVERED_DATASET_FILE_NAME.keys():
    path = join(data_set_path,OVERED_DATASET_FILE_NAME.get(over_name)) 
    # Chargement des données
    save_path = path.replace(".csv", "_rounded.csv")
    if not exists(save_path):
        path = join(data_set_path,OVERED_DATASET_FILE_NAME.get(over_name)) 
        dataset_over = load_over_dataset(path, verbose=verbose)
        dataset_over.to_csv(save_path, index_label="index")
    else:
        print(f"{over_name} ever done")

[load_over_dataset   ]	INFO  (146370, 1982) datas LOAD
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                float64
item_BED LINEN_nb          float64
item_BED LINEN_cash        float64
item_BATHROOM_nb           float64
                            ...
make_TEMPLE ISLAND_cash    float64
make_GHD_nb                float64
make_GHD_cash              float64
amount                     float64
fraud_flag                   int64
Length: 1982, dtype: object
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                   int8
item_BED LINEN_nb             int8
item_BED LINEN_cash        float16
item_BATHROOM_nb              int8
                            ...
make_TEMPLE ISLAND_cash    float16
make_GHD_nb                   int8
make_GHD_cash              float16
amount                     float16
fraud_flag                    int8
Length: 1982, dtype: object
[load_over_dataset   ]	INFO  (146370, 1982) datas LOAD
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                float64
item_BED LINEN_nb          float64
item_BED LINEN_cash        float64
item_BATHROOM_nb           float64
                            ...
make_TEMPLE ISLAND_cash    float64
make_GHD_nb                float64
make_GHD_cash              float64
amount                     float64
fraud_flag                   int64
Length: 1982, dtype: object
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                   int8
item_BED LINEN_nb             int8
item_BED LINEN_cash        float16
item_BATHROOM_nb              int8
                            ...
make_TEMPLE ISLAND_cash    float16
make_GHD_nb                   int8
make_GHD_cash              float16
amount                     float16
fraud_flag                    int8
Length: 1982, dtype: object
[load_over_dataset   ]	INFO  (82950, 1981) datas LOAD
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                float64
item_BED LINEN_nb          float64
item_BED LINEN_cash        float64
item_BATHROOM_nb           float64
                            ...
make_TEMPLE ISLAND_nb      float64
make_TEMPLE ISLAND_cash    float64
make_GHD_nb                float64
make_GHD_cash              float64
fraud_flag                   int64
Length: 1981, dtype: object
[reduce_data_by_typing]	INFO  ID                           int64
Nb_of_items                   int8
item_BED LINEN_nb             int8
item_BED LINEN_cash        float16
item_BATHROOM_nb              int8
                            ...
make_TEMPLE ISLAND_nb         int8
make_TEMPLE ISLAND_cash    float16
make_GHD_nb                   int8
make_GHD_cash              float16
fraud_flag                    int8
Length: 1981, dtype: object
SMOTE_minority ever done
[load_over_dataset   ]	INFO  (146370, 1982) datas LOAD
[reduce_data_by_typing]	INFO  Unnamed: 0                   int64
ID                           int64
Nb_of_items                float64
item_BED LINEN_nb          float64
item_BED LINEN_cash        float64
                            ...
make_TEMPLE ISLAND_nb      float64
make_TEMPLE ISLAND_cash    float64
make_GHD_nb                float64
make_GHD_cash              float64
fraud_flag                   int64
Length: 1982, dtype: object
[reduce_data_by_typing]	INFO  Unnamed: 0                    int8
ID                           int64
Nb_of_items                   int8
item_BED LINEN_nb             int8
item_BED LINEN_cash        float16
                            ...
make_TEMPLE ISLAND_nb         int8
make_TEMPLE ISLAND_cash    float16
make_GHD_nb                   int8
make_GHD_cash              float16
fraud_flag                    int8
Length: 1982, dtype: object
[load_over_dataset   ]	INFO  Unnamed: 0 column to drop.
[load_over_dataset   ]	INFO  (146370, 1981) datas keep SAVE
[load_over_dataset   ]	INFO  (114387, 1983) datas LOAD
[reduce_data_by_typing]	INFO  Unnamed: 0                   int64
ID                           int64
Nb_of_items                float64
item_BED LINEN_nb          float64
item_BED LINEN_cash        float64
                            ...
make_TEMPLE ISLAND_cash    float64
make_GHD_nb                float64
make_GHD_cash              float64
amount                     float64
fraud_flag                   int64
Length: 1983, dtype: object
[reduce_data_by_typing]	INFO  Unnamed: 0                    int8
ID                           int64
Nb_of_items                   int8
item_BED LINEN_nb             int8
item_BED LINEN_cash        float16
                            ...
make_TEMPLE ISLAND_cash    float16
make_GHD_nb                   int8
make_GHD_cash              float16
amount                     float16
fraud_flag                    int8
Length: 1983, dtype: object
[load_over_dataset   ]	INFO  Unnamed: 0 column to drop.
[load_over_dataset   ]	INFO  (114387, 1982) datas keep SAVE